language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
services:
- mysql
before_install: 
#- mysql -e 'CREATE DATABASE IF NOT EXISTS unifit;'
- mysql -u root --password < test/travis.sql
script:
- npm run lint
- npm run test